apiVersion: batch/v1
kind: Job
metadata:
  name: init-social-network
  labels:
    app: init-social-network
spec:
  template:
    metadata:
      name: init-social-network
      labels:
        app: init-social-network
    spec:
      nodeName: {{.Values.nodeName}}
      restartPolicy: Never
      shareProcessNamespace: true
      containers:
      - name: init-social-network
        image: {{ .Values.image }}
        imagePullPolicy: Always
        args:
        - python3
        - init_social_graph.py
        - --graph
        - "{{.Values.args.graph}}"
        - --ip
        - "{{.Values.args.service}}"
        - --port
        - "{{.Values.args.port}}"
{{- if eq .Values.args.compose true }}
        - --compose
{{- end }}