{{- range .Values.services }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
 name: {{.}}
 annotations:
   istio.io/service-account: {{.}}
spec:
 gatewayClassName: istio-mesh
---
{{- end }}