name: mongodb-profile

replicas: 1

ports:
  - port: 27019
    targetPort: 27017
 
container:
  image: mongo
  imageVersion: 4.4.6
  name: hotel-reserv-profile-mongo
  ports:
  - containerPort: 27017
