wrk2:
  duration: 120
  connections: 96
  timeout: 10
  RPS: 3000
  initDelay: 0
  appImage: registry.cn-hangzhou.aliyuncs.com/jkhe/wrk2:1.3
  service: nginx-thrift.social-network:8080
  script: read-user-timeline.lua
