wrk2:
  duration: 20
  connections: 1
  timeout: 100
  RPS: 1
  initDelay: 10
  appImage: registry.cn-hangzhou.aliyuncs.com/jkhe/wrk2:2.6
  service: nginx-thrift.social-network:8080
  script: read-user-timeline.lua
  url: http://nginx-thrift.social-network:8080/wrk2-api/user-timeline/read